# Generated by Django 2.2.1 on 2019-07-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20190704_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peopleinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
