# Generated by Django 2.2.1 on 2019-07-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_peopleinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Peopleinfo',
        ),
    ]
