# Generated by Django 2.2.1 on 2019-07-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20190705_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroinfo',
            name='heroimg',
            field=models.ImageField(blank=True, default=True, null=True, upload_to=''),
        ),
    ]
