# Generated by Django 2.2.1 on 2019-07-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_heroinfo_heroimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='heroimg',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
