# Generated by Django 2.2.1 on 2019-07-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_auto_20190708_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='heroimg',
            field=models.ImageField(blank=True, default='', null=True, upload_to='abs'),
        ),
    ]
